#!/bin/bash
set -e

RAILS_ENV="production"

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the app (default)"
  echo " app:rake <task>    - Execute a rake task."
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

appUpdate() {
    cd /mete
    git pull
    bundle
    rake db:migrate
    rake assets:clean
    rake assets:clobber
    rake assets:precompile
}

appInit() {
  git clone https://github.com/fnordeingang/mete.git /mete
  appUpdate
}

case "$1" in
  app:init)
    appInit
    ;;
  app:start)
    appUpdate
    rails s
    ;;
  app:migrate)
    rake db:migrate
    ;;
  app:rake)
    rake $2
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0

