#!/bin/bash
set -e

RAILS_ENV="production"

cd /mete
git pull
bundle
rake db:migrate
rake assets:clean
rake assets:clobber
rake assets:precompile

appHelp () {
  echo "Available options:"
  echo " app:start          - Starts the app (default)"
  echo " app:rake <task>    - Execute a rake task."
  echo " app:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  app:start)
    rails s
    ;;
  app:migrate)
    rake db:migrate
    ;;
  app:rake)
    rake $2
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        rails s
      fi
    fi
    ;;
esac

exit 0

